name: jsg_inspections
description: JSG-Inspections cross-platform inspection management application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.4.0
  
  # Navigation & Routing
  go_router: ^12.0.0
  auto_route: ^7.7.0
  
  # Database & Storage
  surrealdb: ^0.8.0
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  # Networking & Sync
  dio: ^5.3.0
  connectivity_plus: ^5.0.0
  web_socket_channel: ^2.4.0
  
  # Media & Camera
  camera: ^0.10.0
  image_picker: ^1.0.0
  photo_view: ^0.14.0
  image: ^4.0.0
  
  # QR & Location
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.1.0
  geolocator: ^10.0.0
  
  # File Handling & PDF
  file_picker: ^6.0.0
  path_provider: ^2.1.0
  pdf: ^3.10.0
  printing: ^5.11.0
  
  # Signature & Forms
  signature: ^5.4.0
  flutter_form_builder: ^9.1.0
  
  # AI/ML Integration
  tflite_flutter: ^0.10.0
  
  # Utils & Formatting
  intl: ^0.18.0
  uuid: ^4.0.0
  freezed_annotation: ^2.4.0
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  json_annotation: ^4.8.0
  
  # UI & Design
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  rive: ^0.12.0
  
  # Platform Integration
  device_info_plus: ^9.1.0
  permission_handler: ^11.0.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.3.0
  auto_route_generator: ^7.3.0
  
  # Linting
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  
  # Testing
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700